// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcejjyetzjncyefjqwod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZWpqeWV0empuY3llZmpxd29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjg1ODksImV4cCI6MjA2MTcwNDU4OX0.waKSMOdYUKqoQ5zuxahVsHhFncoIJPEGhNYj9aKJBfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);